<?php
function hugs_menu() {
  $items['hugs/%/%'] = array(
    'title' => 'Hugs',
    'page callback' => 'hugs_hug',
    'page arguments' => array(1,2),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function hugs_theme($existing, $type, $theme, $path) {
  return array(
    'hugs_template' => array(
      'variables' => array(
        'from' => NULL,
        'to' => NULL,
      ),
      'template' => 'hugs_template',
    ),
  );    
} 

function hugs_hug($from = '', $to = '') {
  $output = array(
    '#theme' => 'hugs_template',
    '#type' => 'markup',
    '#from' => t($from),
    '#to' => t($to),
  );
  return $output;
}


