<?php
function hugs_menu() {
  $items['hugs/%/%'] = array(
    'title' => 'Hugs',
    'page callback' => 'hugs_hug',
    'page arguments' => array(1,2),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function hugs_theme($existing, $type, $theme, $path) {
  return array(
    'hugs_hug' => array(
      'variables' => array(
        'from' => NULL,
        'to' => NULL,
      ),
    ),
  );    
} 

function hugs_hug($from = '', $to = '') {
  return theme('hugs_hug', array('from' => $from, 'to' => $to));
}

function theme_hugs_hug($variables) {
  $output = "<p><strong>" . $variables['from'] . "</strong> hugs <em>" . $variables['to'] . "</em>.";
  return $output;
}

